# Generated by Django 5.0.4 on 2024-05-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('country', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='authors')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('pages', models.IntegerField(default=0)),
                ('date_published', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=10)),
                ('image', models.ImageField(upload_to='books')),
                ('paper_format', models.CharField(max_length=2)),
                ('cover', models.CharField(choices=[('hard', 'hard'), ('soft', 'soft')], default='hard', max_length=4)),
                ('authors', models.ManyToManyField(to='books.author')),
                ('genre', models.ManyToManyField(to='books.genre')),
            ],
        ),
    ]
